name       : python-pyproject2setuppy
version    : 22
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/p/pyproject2setuppy/pyproject2setuppy-22.tar.gz : ae40fa080617174b4627d2728018ea2d8ecedc514cccfaaf1f68a08f9ebfef1f
license    : GPL-2.0-or-later # CHECK ME
component  : programming.python
summary    : Build pyproject.toml-based (flit, poetry) projects using setuptools
description: |
    Build pyproject.toml-based (flit, poetry) projects using setuptools
builddeps  :
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
